"use client";

import { useCallback, useState } from "react";
import { AlertCircle, Loader2, RefreshCw, ServerOff, Sparkles } from "lucide-react";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

interface DigestViewProps {
  /** Titles of recently-changed notes, sent to the local LLM for a theme summary. */
  changedTitles: string[];
}

/** Shape returned by POST /api/digest. */
interface SummaryResult {
  summary: string;
  code?: "unavailable" | "timeout" | "error";
}

type ViewState =
  | { status: "idle" }
  | { status: "loading" }
  | { status: "ready"; summary: string }
  | { status: "unavailable" }
  | { status: "empty"; reason: "timeout" | "error" | "network" };

export function DigestView({ changedTitles }: DigestViewProps) {
  const [state, setState] = useState<ViewState>({ status: "idle" });
  const hasTitles = changedTitles.length > 0;

  const summarize = useCallback(async () => {
    setState({ status: "loading" });
    try {
      const res = await fetch("/api/digest", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ titles: changedTitles }),
        cache: "no-store",
      });
      if (!res.ok) {
        setState({ status: "empty", reason: "error" });
        return;
      }
      const data = (await res.json()) as SummaryResult;
      if (data.code === "unavailable") {
        setState({ status: "unavailable" });
        return;
      }
      if (data.summary.trim()) {
        setState({ status: "ready", summary: data.summary.trim() });
        return;
      }
      setState({
        status: "empty",
        reason: data.code === "timeout" ? "timeout" : "error",
      });
    } catch {
      setState({ status: "empty", reason: "network" });
    }
  }, [changedTitles]);

  const isLoading = state.status === "loading";

  return (
    <Card>
      <CardHeader>
        <CardTitle className="font-display flex items-center gap-2 text-lg">
          <Sparkles className="text-chart-4 h-4 w-4" />
          Theme summary
        </CardTitle>
        <CardDescription>
          A short prose summary of what the recent work is about, generated by
          your local model.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="flex flex-wrap items-center gap-3">
          <Button
            type="button"
            onClick={summarize}
            disabled={isLoading || !hasTitles}
            aria-busy={isLoading}
          >
            {isLoading ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" aria-hidden="true" />
                Summarizing…
              </>
            ) : (
              <>
                <Sparkles className="h-4 w-4" aria-hidden="true" />
                Summarize recent themes
              </>
            )}
          </Button>
          {!hasTitles && (
            <span className="text-muted-foreground text-sm">
              No recent changes to summarize.
            </span>
          )}
        </div>

        <div aria-live="polite">
          {state.status === "loading" && (
            <span className="sr-only">Generating summary…</span>
          )}

          {state.status === "ready" && (
            <div className="bg-muted/40 space-y-2 rounded-lg p-4 ring-1 ring-foreground/5">
              <p className="text-foreground text-sm leading-relaxed">
                {state.summary}
              </p>
              <p className="text-muted-foreground/70 flex items-center gap-1.5 text-xs">
                <Sparkles className="h-3 w-3" aria-hidden="true" />
                Generated locally — never leaves your machine.
              </p>
            </div>
          )}

          {state.status === "unavailable" && (
            <div className="text-muted-foreground flex items-start gap-2.5 rounded-lg border border-dashed p-4 text-sm">
              <ServerOff className="mt-0.5 h-4 w-4 shrink-0" aria-hidden="true" />
              <span>Start Ollama to generate a summary.</span>
            </div>
          )}

          {state.status === "empty" && (
            <div className="flex flex-col items-start gap-2.5 rounded-lg border border-dashed p-4">
              <p className="text-muted-foreground flex items-start gap-2.5 text-sm">
                <AlertCircle
                  className="mt-0.5 h-4 w-4 shrink-0"
                  aria-hidden="true"
                />
                <span>
                  {state.reason === "timeout"
                    ? "The model took too long to respond."
                    : state.reason === "network"
                      ? "Couldn't reach the summary service."
                      : "The model didn't return a summary."}
                </span>
              </p>
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={summarize}
                disabled={isLoading}
              >
                <RefreshCw className="h-3.5 w-3.5" aria-hidden="true" />
                Try again
              </Button>
            </div>
          )}
        </div>
      </CardContent>
    </Card>
  );
}
